# Generated by Django 5.2.16 on 2026-07-12 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='reaction_type',
            field=models.CharField(choices=[('Like', 'Like'), ('Love', 'Love'), ('Angry', 'Angry'), ('Haha', 'Haha')], db_index=True, default='Like', max_length=10),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['content_type', 'object_id', 'reaction_type'], name='likes_content_d5a69f_idx'),
        ),
    ]
